config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 # get '/post', to: 'posts#new'
 # post '/post', to: 'posts#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :tags
  resources :posts do
    get '/addtag', to: 'tags#newbind'
    post '/addtag', to: 'tags#createbind'
    delete '/tag/:id', to: 'tags#destroybind', as: 'tag_destroy'
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def new
        @tag = Tag.new
    end

    def edit
        @tag = Tag.find(params[:id])
    end

    def update
        @tag = Tag.find(params[:id])
        @tag.update(tags_params)
        @tag.save
        redirect_to tags_path
    end

    def index
        @tags = Tag.all
    end

    def create
        @tag = Tag.new(tags_params)
        if @tag.save
            flash[:success] = "Erfolgreich einen Tag erstellt"
            redirect_to root_path
          else
            render 'new'
          end
    end

    def newbind
        @post = Post.find(params[:post_id])
        @tags = Tag.all
        @newtags = []
        @tags.each do |tag| 
            if !@post.tags.include?(tag)
                @newtags.push(tag)
            end
        end
        @tag = @post.tags.new
        
    end

    def createbind
        @post = Post.find(params[:post_id])
        @tag = Tag.find(params[:tag][:id])
        @post.tags.push(@tag)
        @post.save
        redirect_to post_path(@post)
    end

    def destroybind
        @post = Post.find(params[:post_id])
        @tag = Tag.find(params[:id])
        @post.tags.delete(@tag)
        @post.save
        redirect_to post_path(@post)
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
        redirect_to tags_path
    end

    private

    def tags_params
    params.require(:tag).permit(:name)
    end

    def bind_params
        params.permit(:tag)


    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<% provide(:title, 'Tag editieren') %>
<h1>
    Den Tag editieren
</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= form_for(@tag, url: tag_path(@tag), method: "PATCH") do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    

        <%= f.submit "Ändern", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/tags/index.html.erb
<% provide(:title, 'Tags') %>
<h1>Alle Tags</h1>
<ul class="nostyle">
    <% @tags.each do |tag| %>
        <div class="row center post-section-div">
            <li><h2><%= tag.name %></h2>
                <%= link_to "Bearbeiten", edit_tag_path(tag), class: "btn btn-primary" %>
                <%= link_to "Löschen", tag_path(tag), method: "DELETE", class: "btn btn-primary" %>
            </li>
        </div>
    <% end %>
</ul>

app/views/tags/new.html.erb
<% provide(:title, 'Erstelle Tag') %>
<h1>Erstelle Tag</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@tag, url: tags_new_path) do |f| %>
            

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.submit "Erstelle Tag", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/tags/newbind.html.erb
<% provide(:title, "Tag hinzufügen") %>
<h1>
    Tag hinzufügen
</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@tag, url: post_addtag_path) do |f| %>
            <%= render 'shared/error_messages_posts' %>

            <%= f.label :text %>
            <%= f.select(:id, @newtags.collect {|p| [p.name, p.id]
            })%>
        

            <%= f.submit "Posten", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>