config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 # get '/post', to: 'posts#new'
 # post '/post', to: 'posts#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :tags
  resources :posts do
    get '/addtag', to: 'tags#newbind'
    post '/addtag', to: 'tags#createbind'
    delete '/tag/:id', to: 'tags#destroybind', as: 'tag_destroy'
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence:true, length: {maximum: 80}
    validates :text, presence:true, length: {minimum: 50}
    
    has_many :comments
    has_and_belongs_to_many :tags
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
      flash[:success] = "Erfolgreich gepostet"
      redirect_to @post
    else
      render 'new'
    end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      @post.update(post_params)
      @post.save
      redirect_to @post
    end

    def index
      @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end

    private

  def post_params
    params.require(:post).permit(:text, :title)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% provide(:title, 'Post editieren') %>
<h1>
    Den Post editieren
</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= form_for(@post, url: post_path(@post), method: "PATCH") do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :text %>
        <%= f.text_area :text, class: 'form-control' %>
    

        <%= f.submit "Ändern", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'Posts') %>
<h1>Alle Posts</h1>
<ul class="nostyle">
    <% @posts.each do |post| %>
        <div class="row center post-section-div">
            <li><h2><%= post.title %></h2>
                <%= link_to "Anzeigen", post_path(post), class: "btn btn-primary" %>
            </li>
        </div>
        <br>
        <div class="row center text-width-post">
            <li><%= post.text %></li>
        </div>
    <% end %>
</ul>

app/views/posts/new.html.erb
<% provide(:title, "Etwas Posten") %>
<h1>
    Einen Post erstellen
</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@post, url: posts_path) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>

            <%= f.label :text %>
            <%= f.text_area :text, class: 'form-control' %>
        

            <%= f.submit "Posten", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<%= provide(:title, "Post") %>
<h1>
    Titel: <%= @post.title %>
</h1>
<div class="center text-width-post"><%= @post.text %></div>
<br>
<br>
<div class="center row">
    <%= link_to "Bearbeiten", edit_post_path(@post), class: "btn btn-primary" %>
    <%= link_to "Löschen", post_path(@post), method: "DELETE", class: "btn btn-primary" %>
</div>

<div class="post-section-div">
<h2>Tags</h2>
    <% @post.tags.each do |tag| %>
         <div class="center tag row" >
            <%= tag.name%>
            <%= link_to "Entfernen", post_tag_destroy_path(@post, tag), method: "DELETE" %>
         </div>
    <% end %>
    <br>
    <div class="center tag"><%= link_to "Tag hinzufügen",  post_addtag_path(@post), class: "btn btn-primary"%></div>
</div>
<div class="post-section-div">
    <h2> Kommentare </h2>
    <% @post.comments.each do |comment| %>
        <div class="row center comment" >
            <%= comment.text%>
        </div>
        <div class="row center comment">
            <%= link_to "Bearbeiten", edit_post_comment_path(@post,comment), class: "btn" %>
            <%= link_to "Löschen", post_comment_path(@post, comment), method: "DELETE", class: "btn" %>
        </div>
    <% end %>
    <br>
    <div class="row center">
        <%= link_to "Kommentieren",  new_post_comment_path(@post), class: "btn btn-primary"%>
    </div>
</div>