config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 # get '/post', to: 'posts#new'
 # post '/post', to: 'posts#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :tags
  resources :posts do
    get '/addtag', to: 'tags#newbind'
    post '/addtag', to: 'tags#createbind'
    delete '/tag/:id', to: 'tags#destroybind', as: 'tag_destroy'
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="https://michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                Posts <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Alle Posts", posts_path %></li>
                <li><%= link_to "Neuer Post", new_post_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                Tags <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Alle Tags", tags_path %></li>
                <li><%= link_to "Neuer Tag", new_tag_path %></li>
              </ul>
            </li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Benutzer", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profil", current_user %></li>
                  <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Ausloggen", logout_path, method: 'DELETE' %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Einloggen", login_path %></li>
            <% end %>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>